### ISSUE TITLE
How to batch upload data?

### ISSUE THREAD

**Issue by schaefed** [hylkevds/FROST-Server.Plugin.GeoTech#1]
This might be obvious, sorry if it is so, but I am unfortunately unable to fill the database with the example data provided in `scripts/BatchUploadTemplate.json`. When running the following command against a local (docker compose) based instance: 

```shell
curl -X POST -H "Content-Type: application/json" -d @scripts/BatchUploadTemplate.json http://admin:admin@localhost:8080/FROST-Server/v1.1/?$batch
```
I get the following error message back:
```shell
{"code":400,"type":"error","message":"POST only allowed to Collections."}
```
I am aware of the following [document](https://fraunhoferiosb.github.io/FROST-Server/extensions/JsonBatchRequest.html) but couldn't figure out the correct command either...A hint would be highly appreciated.

**Comment by hylkevds** [comment]
There should not be a `?` in your URL. `$batch` is the path to post to, not a query parameter.

**Comment by schaefed** [comment]
I also tried that and unfortunately got the same error response with:
```shell
curl -X POST -H "Content-Type: application/json" -d @scripts/BatchUploadTemplate.json http://admin:admin@localhost:8080/FROST-Server/v1.1/$batch
```

**Comment by hylkevds** [comment]
`$` is a special character in shell scripts, denoting the start of a variable that is to be expanded. So `$batch` will be expanded with the contents of the environment variable `batch`.
You have to put single-quotes around your URL to stop the shell from expanding.

**Comment by schaefed** [comment]
This did the job! Thanks and sorry for bothering...
